### ISSUE TITLE
Update Vaults and Snippets path

### ISSUE THREAD

**Issue by SalGnt** [codervault/codervault#8]
With the introduction of user profiles, vaults and snippets must have a url path that contains the username of the owner.

**Comment by CGA1123** [comment]
Wrapping the routes for `vaults` and `snippets` in `scope ':username' do ... end` 
should set up the routes up.

**Comment by mrvncaragay** [comment]
I'm going to include this changes in my next PR, if you  haven't worked on it @CGA1123 

@SalGnt  i think we should also change `vaults' id` to `vaults' name` and `snippet's id` to `snippet's name pr language`

**Comment by CGA1123** [comment]
I haven't worked on this, feel free! :)

**Comment by mrvncaragay** [comment]
@CGA1123 I've added `scope ':username' do...` would require all the path a `username` I've added `default` like this `scope ':username', defaults: { username: 'default' } do...` so that we only provide real username to path such as `:show, :index` is this sufficient enough? is there a way to require 'username' only to `:show and :index`? i feel like this should be a way hehe

**Comment by CGA1123** [comment]
@mrvncaragay I don't see the reason for only prefixing _some_ paths with `:username`, keeping it consistent across all of them makes more sense to me. Unless I'm misunderstanding your point.

[Here](https://gist.github.com/CGA1123/dd36a6f44fc841bd96f066c6f3454756) is the output from `rake routes` for me.

**Comment by mrvncaragay** [comment]
@CGA1123 yup i have the same output but with defaults. So that we only have to supply username to a certain path such as index and show. Gotta re test the controller again hehe. Thanks for the input

**Comment by mrvncaragay** [comment]
I've added this fix here #9
